/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstore.ui.components;

import javax.swing.SwingUtilities;
import musicstore.datastructures.AccountInfo;
import musicstore.ui.browseproducts.MusicStoreBrowseProductsUI;
import musicstore.ui.cart.MusicStoreCartUI;

/**
 *
 * @author jablo
 */
public class MusicStoreAccountDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form MusicStoreAccountDataPanel
     */
    public MusicStoreAccountDataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountDataAvatar = new musicstore.ui.components.ImagePanel();
        accountDataYouAreLoggedAsLabel = new javax.swing.JLabel();
        accountDataFullName = new javax.swing.JLabel();
        accountDataInCartLabel = new javax.swing.JLabel();
        accountDataCartState = new javax.swing.JLabel();
        accountDataTotalPriceLabel = new javax.swing.JLabel();
        accountDataTotalPrice = new javax.swing.JLabel();
        accountCartButton = new javax.swing.JButton();

        javax.swing.GroupLayout accountDataAvatarLayout = new javax.swing.GroupLayout(accountDataAvatar);
        accountDataAvatar.setLayout(accountDataAvatarLayout);
        accountDataAvatarLayout.setHorizontalGroup(
            accountDataAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        accountDataAvatarLayout.setVerticalGroup(
            accountDataAvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        accountDataYouAreLoggedAsLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        accountDataYouAreLoggedAsLabel.setText("You are logged as:");

        accountDataFullName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        accountDataFullName.setText("Firstname Lastname");

        accountDataInCartLabel.setText("In cart:");

        accountDataCartState.setText("x items");

        accountDataTotalPriceLabel.setText("Total price:");

        accountDataTotalPrice.setText("xxx cebulionów");

        accountCartButton.setText("Your cart");
        accountCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountDataYouAreLoggedAsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataFullName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountDataInCartLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataCartState))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(accountCartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(accountDataTotalPriceLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountDataTotalPrice))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(accountDataAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountDataYouAreLoggedAsLabel)
                            .addComponent(accountDataFullName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountDataInCartLabel)
                            .addComponent(accountDataCartState))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountDataTotalPriceLabel)
                            .addComponent(accountDataTotalPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountCartButton))
                    .addComponent(accountDataAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCartButtonActionPerformed
        // TODO add your handling code here:
        MusicStoreBrowseProductsUI topFrame;
        topFrame = (MusicStoreBrowseProductsUI) SwingUtilities.getWindowAncestor(this);
            
        java.awt.EventQueue.invokeLater(() -> {
            MusicStoreCartUI cartUI = new MusicStoreCartUI();
            cartUI.setVisible(true);
            cartUI.SetContext(topFrame.GetProducts(), topFrame.GetAccount());
        });
        
        topFrame.setVisible(false);
        topFrame.dispose();
        
    }//GEN-LAST:event_accountCartButtonActionPerformed


    public void SetAccountInfo(AccountInfo account)
    {
        accountDataCartState.setText(Integer.toString(account.getCartState()));
        accountDataFullName.setText(account.getFirstName() + " " + account.getLastName());
        accountDataTotalPrice.setText(Float.toString(account.getTotalPrice()));
        accountDataAvatar.SetImagePath(account.getAvatarPath());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountCartButton;
    private musicstore.ui.components.ImagePanel accountDataAvatar;
    private javax.swing.JLabel accountDataCartState;
    private javax.swing.JLabel accountDataFullName;
    private javax.swing.JLabel accountDataInCartLabel;
    private javax.swing.JLabel accountDataTotalPrice;
    private javax.swing.JLabel accountDataTotalPriceLabel;
    private javax.swing.JLabel accountDataYouAreLoggedAsLabel;
    // End of variables declaration//GEN-END:variables
}
