CREATE TABLE CLIENT (
  ID NUMBER(10) PRIMARY KEY,
  FIRSTNAME VARCHAR2(1000 CHAR) NOT NULL,
  LASTNAME VARCHAR2(1000 CHAR) NOT NULL,
  EMAIL VARCHAR2(1000 CHAR) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(1000 CHAR) NOT NULL
);

CREATE SEQUENCE CLIENT_SEQ NOCACHE;

CREATE TRIGGER CLIENT_BI
  BEFORE INSERT ON CLIENT
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT CLIENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE TABLE GUITAR (
  ID NUMBER(10) PRIMARY KEY,
  BODY VARCHAR2(1000 CHAR) NOT NULL,
  PRICE NUMBER NOT NULL,
  NAME VARCHAR2(1000 CHAR) UNIQUE NOT NULL,
  DESCRIPTION CLOB,
  STORAGESTATE NUMBER(10) NOT NULL
);

CREATE SEQUENCE GUITAR_SEQ NOCACHE;

CREATE TRIGGER GUITAR_BI
  BEFORE INSERT ON GUITAR
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT GUITAR_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE TABLE CARTITEM (
  ID NUMBER(10) PRIMARY KEY,
  CLIENT NUMBER(10) NOT NULL,
  GUITAR NUMBER(10) NOT NULL
);

ALTER TABLE CARTITEM ADD CONSTRAINT FK_CARTITEM__CLIENT FOREIGN KEY (CLIENT) REFERENCES CLIENT (ID);

ALTER TABLE CARTITEM ADD CONSTRAINT FK_CARTITEM__GUITAR FOREIGN KEY (GUITAR) REFERENCES GUITAR (ID);

CREATE SEQUENCE CARTITEM_SEQ NOCACHE;

CREATE TRIGGER CARTITEM_BI
  BEFORE INSERT ON CARTITEM
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT CARTITEM_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE TABLE PURCHASE (
  ID NUMBER(10) PRIMARY KEY,
  CLIENT NUMBER(10) NOT NULL,
  DATE DATE NOT NULL,
  TOTALPRICE NUMBER NOT NULL
);

ALTER TABLE PURCHASE ADD CONSTRAINT FK_PURCHASE__CLIENT FOREIGN KEY (CLIENT) REFERENCES CLIENT (ID);

CREATE SEQUENCE PURCHASE_SEQ NOCACHE;

CREATE TRIGGER PURCHASE_BI
  BEFORE INSERT ON PURCHASE
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT PURCHASE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE TABLE GUITAR_PURCHASE (
  GUITAR NUMBER(10) NOT NULL,
  PURCHASE NUMBER(10) NOT NULL,
  PRIMARY KEY (GUITAR, PURCHASE)
);

ALTER TABLE GUITAR_PURCHASE ADD CONSTRAINT FK_GUITAR_PURCHASE__GUITAR FOREIGN KEY (GUITAR) REFERENCES GUITAR (ID);

ALTER TABLE GUITAR_PURCHASE ADD CONSTRAINT FK_GUITAR_PURCHASE__PURCHASE FOREIGN KEY (PURCHASE) REFERENCES PURCHASE (ID)
