/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstore.ui.buyproduct;

import musicstore.datastructures.ProductInfo;

/**
 *
 * @author jablo
 */
public class MusicStoreProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public MusicStoreProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImage = new musicstore.ui.components.ImagePanel();
        productName = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productDescriptionLabel = new javax.swing.JLabel();
        productDescription = new javax.swing.JScrollPane();
        productDescriptionText = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Product"));

        javax.swing.GroupLayout productImageLayout = new javax.swing.GroupLayout(productImage);
        productImage.setLayout(productImageLayout);
        productImageLayout.setHorizontalGroup(
            productImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        productImageLayout.setVerticalGroup(
            productImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        productName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        productName.setText("productName");

        productPriceLabel.setText("Price:");

        productPrice.setText("<price>");

        productDescriptionLabel.setText("Description:");

        productDescription.setBorder(null);
        productDescription.setOpaque(false);

        productDescriptionText.setColumns(20);
        productDescriptionText.setRows(5);
        productDescriptionText.setText("<some description>\n");
        productDescriptionText.setBorder(null);
        productDescriptionText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        productDescriptionText.setEnabled(false);
        productDescriptionText.setOpaque(false);
        productDescription.setViewportView(productDescriptionText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(productPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productPrice)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(productDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(productPriceLabel)
                        .addComponent(productDescriptionLabel)
                        .addComponent(productPrice))
                    .addComponent(productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void SetProductInfo(ProductInfo product)
    {
        productDescriptionText.setText(product.getProductDescription());
        productName.setText(product.getProductName());
        productPrice.setText(Float.toString(product.getProductPrice()));
        productImage.SetImagePath(product.getProductImagePath());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane productDescription;
    private javax.swing.JLabel productDescriptionLabel;
    private javax.swing.JTextArea productDescriptionText;
    private musicstore.ui.components.ImagePanel productImage;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productPriceLabel;
    // End of variables declaration//GEN-END:variables
}

