/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstore.ui.browseproducts;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import musicstore.datastructures.AccountInfo;
import musicstore.datastructures.FilterInfo;
import musicstore.datastructures.ProductInfo;
import musicstore.logic.AccountInfoRetriever;
import musicstore.logic.ProductsRetriever;
import musicstore.ui.buyproduct.MusicStoreBuyProductUI;

/**
 *
 * @author jablo
 */
public class MusicStoreBrowseProductsUI extends javax.swing.JFrame {

    private List<ProductInfo> productsInfo = null;
    private AccountInfo account;
    /**
     * Creates new form MusicStoreBrowseProductsUI
     */
    public MusicStoreBrowseProductsUI() {
        initComponents();
        LoadData(ProductsRetriever.GetProducts(null));
    }
    
    public List<ProductInfo> GetProducts(){
        return this.productsInfo;
    }
    
    public AccountInfo GetAccount(){
        return this.account;
    }
    
    public void SetContext(AccountInfo account){
        this.account = account;
        musicStoreAccountDataPanel.SetAccountInfo(account);
    }

    public void LoadData(List<ProductInfo> products){
        this.productsInfo = products;
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        
        for(int i = model.getRowCount() - 1; i >= 0; i--){
            model.removeRow(i);
        }
        
        products.stream().forEach((ProductInfo product) -> {
            model.addRow(new Object[]{product.getProductName(), (product.isProductAvailability() ? "Yes" : "No"), String.valueOf(product.getProductPrice())});
        });
    }
    
    public void FilterData(FilterInfo filters){
        LoadData(ProductsRetriever.GetProducts(filters));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductTableScrollable = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        musicStoreBrowseFilters1 = new musicstore.ui.browseproducts.MusicStoreBrowseFilters();
        musicStoreAccountDataPanel = new musicstore.ui.components.MusicStoreAccountDataPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Availablity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        ProductTableScrollable.setViewportView(ProductTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductTableScrollable, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(musicStoreBrowseFilters1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(musicStoreAccountDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicStoreBrowseFilters1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicStoreAccountDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ProductTableScrollable, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:
        int row = ProductTable.rowAtPoint(evt.getPoint());
        java.awt.EventQueue.invokeLater(() -> {
            MusicStoreBuyProductUI buyProduct = new MusicStoreBuyProductUI();
            buyProduct.setVisible(true);
            buyProduct.LoadData(productsInfo.get(row), AccountInfoRetriever.GetAccountInfo(account.getId()));
            buyProduct.setContext(productsInfo);
        });
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ProductTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicStoreBrowseProductsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MusicStoreBrowseProductsUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JScrollPane ProductTableScrollable;
    private musicstore.ui.components.MusicStoreAccountDataPanel musicStoreAccountDataPanel;
    private musicstore.ui.browseproducts.MusicStoreBrowseFilters musicStoreBrowseFilters1;
    // End of variables declaration//GEN-END:variables
}
