/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstore.ui.browseproducts;

import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import musicstore.datastructures.FilterInfo;
import musicstore.logic.FiltersRetriever;

/**
 *
 * @author jablo
 */
public class MusicStoreBrowseFilters extends javax.swing.JPanel {

    /**
     * Creates new form MusicStoreBrowseFilters
     */
    public MusicStoreBrowseFilters() {
        initComponents();
        setFilters();
    }

    private void setFilters(){
        Map<String, List<String>> filters = FiltersRetriever.GetFilters();
        setBodyComboBox(filters.get("Body"));
    }
    
    private void setBodyComboBox(List<String> bodies){
        bodies.stream().forEach(body -> {
            DefaultComboBoxModel model = (DefaultComboBoxModel) BodyComboBox.getModel();
            model.addElement(body);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchLabel = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        BodyLabel = new javax.swing.JLabel();
        BodyComboBox = new javax.swing.JComboBox();
        FilterButton = new javax.swing.JButton();
        MinPriceLabel = new javax.swing.JLabel();
        MaxPriceLabel = new javax.swing.JLabel();
        MinPriceTextField = new javax.swing.JTextField();
        MaxPriceTextField = new javax.swing.JTextField();

        SearchLabel.setText("Search:");

        BodyLabel.setText("Body:");

        FilterButton.setText("Search");
        FilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterButtonActionPerformed(evt);
            }
        });

        MinPriceLabel.setText("Min. price");

        MaxPriceLabel.setText("Max. price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchLabel)
                            .addComponent(BodyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchTextField)
                            .addComponent(BodyComboBox, 0, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MinPriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MinPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MaxPriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(FilterButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchLabel)
                    .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinPriceLabel)
                    .addComponent(MinPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BodyLabel)
                    .addComponent(BodyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxPriceLabel)
                    .addComponent(MaxPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FilterButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterButtonActionPerformed
        // TODO add your handling code here:
        FilterInfo filters = new FilterInfo();
        filters.setProductName(SearchTextField.getText());
        filters.setBody((String) BodyComboBox.getSelectedItem());
        filters.setPriceMin(MinPriceTextField.getText().equals("") ? Float.MIN_VALUE : Float.parseFloat(MinPriceTextField.getText()));
        filters.setPriceMax(MaxPriceTextField.getText().equals("") ? Float.MAX_VALUE : Float.parseFloat(MaxPriceTextField.getText()));
        
        MusicStoreBrowseProductsUI topFrame;
        topFrame = (MusicStoreBrowseProductsUI) SwingUtilities.getWindowAncestor(this);
        topFrame.FilterData(filters);
    }//GEN-LAST:event_FilterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BodyComboBox;
    private javax.swing.JLabel BodyLabel;
    private javax.swing.JButton FilterButton;
    private javax.swing.JLabel MaxPriceLabel;
    private javax.swing.JTextField MaxPriceTextField;
    private javax.swing.JLabel MinPriceLabel;
    private javax.swing.JTextField MinPriceTextField;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JTextField SearchTextField;
    // End of variables declaration//GEN-END:variables
}
